# Generated by Django 6.0.3 on 2026-03-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayment',
            name='mp_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID pagamento MP'),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='mp_preference_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID preferência MP'),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='mp_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='status MP'),
        ),
        migrations.AddField(
            model_name='payment',
            name='mp_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID pagamento MP'),
        ),
        migrations.AddField(
            model_name='payment',
            name='mp_preference_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID preferência MP'),
        ),
        migrations.AddField(
            model_name='payment',
            name='mp_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='status MP'),
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='method',
            field=models.CharField(choices=[('cash', 'Dinheiro'), ('pix', 'PIX'), ('credit_card', 'Cartão de Crédito'), ('debit_card', 'Cartão de Débito'), ('mercadopago', 'MercadoPago')], max_length=20, verbose_name='método'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Dinheiro'), ('pix', 'PIX'), ('credit_card', 'Cartão de Crédito'), ('debit_card', 'Cartão de Débito'), ('mercadopago', 'MercadoPago')], max_length=20, verbose_name='método'),
        ),
    ]
