# Generated by Django 6.0.3 on 2026-03-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_historicalpayment_mp_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayment',
            name='mp_installments',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='parcelas'),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='mp_status_detail',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='detalhe status MP'),
        ),
        migrations.AddField(
            model_name='payment',
            name='mp_installments',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='parcelas'),
        ),
        migrations.AddField(
            model_name='payment',
            name='mp_status_detail',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='detalhe status MP'),
        ),
    ]
